import Head from "next/head";
import { useEffect, useState } from "react";
import Layout from "../../components/Layout/Layout";
import Card from "../../components/Card/Card";
import style from "./Favorites.module.css";

function Favorites() {
    const [restaurants, setRestaurants] = useState([]);

    const getRestaurants = () => {
        fetch('/api/restaurants')
        .then((res) => res.json())
        .then((data) => {
            setRestaurants(data);
        })
    };

    useEffect(()=>{
        getRestaurants();
    }, []);
    return <>
            <Head>
                <title>Hunger App | Favorite</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <section>
                    <div className={style.cards}>
                        {
                            restaurants.map(restaurant =>{
                                return restaurant.menus.map(menu=>{
                                    return <Card key={menu.id} description={menu.description} name={menu.menuname} srcImg={menu.images[0]} />
                                })
                            }) 
                        }
                    </div>
                </section>
            </Layout>
        </>
}

export default Favorites;
