import Head from "next/head";
import { useEffect, useState } from "react";
import Layout from "../../components/Layout/Layout";
import axios from 'axios';
import Card from "../../components/Card/Card";
import style from "./Favorites.module.css";

function Favorites() {
    const [foods, setFoods] = useState([]);
    const [restaurants, setRestaurants] = useState([]);

    const getFoods = async () => {
        await axios
        .get('https://foodbukka.herokuapp.com/api/v1/menu')
        .then(res => res.data.Result)
        .then(data => {
            setFoods(data);
        })
        .catch(err => console.log(err.message));
    };

    const getRestaurants = () => {
        fetch('/api/restaurants')
        .then((res) => res.json())
        .then((data) => {
            setRestaurants(data);
        })
    };

    useEffect(()=>{
        getFoods();
        getRestaurants();
    }, []);
    return <>
            <Head>
                <title>Hunger App | Favorite</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <section>
                    <div className={style.cards}>
                        {
                            restaurants.map(restaurant =>{
                                return restaurant.menus.map(menu=>{
                                    return <Card navigate={`/favorites/${menu.id}`} key={menu.id} description={menu.description} name={menu.menuname} srcImg={menu.images[1]} />
                                })
                            }) 
                        }
                    </div>
                </section>
            </Layout>
        </>
}

export default Favorites;
