import Head from 'next/head'
import { useEffect, useState } from "react";
import Layout from "../../components/Layout/Layout";
import style from "./About.module.css";
import Card from "../../components/Card/Card";

function Galery() {
    const [restaurantsAsyncAwait, setRestaurantsAsyncAwait] = useState([])

    const fetchApiAsyncAwait = async () => {
        try{
            const response = await fetch('/api/restaurants');
            const data = await response.json();
            setRestaurantsAsyncAwait(data) 
        }catch(err){
            console.error('Error' + err);
        }
    };

    useEffect( ()=>{
        fetchApiAsyncAwait();
    },[])

return <>
        <Head>
            <title>Hunger App | About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Layout>
            <section className={style.products}>
                <h4 className={style.section_title}></h4>
                <div className={style.cards}>
                    {
                        restaurantsAsyncAwait.map(restaurant =>{
                        return(
                            <Card id={restaurant.id} key={restaurant.id} description={restaurant.description} location={restaurant.location} name={restaurant.name} srcImg={restaurant.image} rating={restaurant.rating}/>
                        )
                        })
                    }
                </div>
            </section>
        </Layout>
    </>;
}

export default Galery;
