import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Card from "../../../components/Card/Card";
import style from "./Favorite.module.css";
import Layout from "../../../components/Layout/Layout";
import { restaurants } from "../../../data/restaurants";

function Favorite() {
    const [foods, setFoods] = useState([]);
    const router = useRouter();
    const { id } = router.query;

    useEffect(() => {
        const result = restaurants.filter((restaurant) => {
            return restaurant.id == parseInt(id);
        });
        setFoods(result);
    }, [id]);

    return (
        <>
            <Head>
                <title>Hunger App | Favorite</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <section>
                    <h2 className={style.title}>List Menu Makanan { foods.length != 0 && foods[0].name }</h2>
                    <div className={style.cards}>

                        {

                            foods.length != 0 &&
                            foods[0].menus.map(menu => {
                            return <Card description={menu.description} name={menu.menuname} srcImg={menu.images} key={menu.id} />
                            })
                        }
                        
                    </div>
                </section>
            </Layout>
            </>
        );
    }

    export default Favorite;
